import { TaskStatusEnum } from "../Lib/Enums/TaskStatusEnum";
import { ITaskItemBase } from "./Interfaces/ITaskItemBase";

export const dummyTaskDataCollection: ITaskItemBase[] = [
  {
    id: 1,
    title: "Design login page",
    status: TaskStatusEnum.Created,
    shortDescription: "Create wireframes and design for login page UI.",
    assignedUserId: 0,
    taskTypeId: 1,
  },
  {
    id: 2,
    title: "Implement authentication",
    status: TaskStatusEnum.Created,
    shortDescription: "Setup JWT authentication for the backend API.",
    assignedUserId: 1,
    taskTypeId: 2,
  },
  {
    id: 3,
    title: "Write unit tests",
    status: TaskStatusEnum.Created,
    shortDescription: "Add unit tests for user service and auth service.",
    assignedUserId: 0,
    taskTypeId: 3,
  },
  {
    id: 4,
    title: "Fix navbar bug",
    status: TaskStatusEnum.Created,
    shortDescription: "Navbar dropdown was not working on mobile devices.",
    assignedUserId: 2,
    taskTypeId: 1,
  },
  {
    id: 5,
    title: "Update README",
    status: TaskStatusEnum.Created,
    shortDescription: "Add new instructions for environment setup.",
    assignedUserId: 1,
    taskTypeId: 4,
  },
  {
    id: 6,
    title: "Deploy to staging",
    status: TaskStatusEnum.InProgress,
    shortDescription: "Deploy the latest changes to the staging environment.",
    assignedUserId: 0,
    taskTypeId: 2,
  },
  {
    id: 7,
    title: "Research new frontend framework",
    status: TaskStatusEnum.InProgress,
    shortDescription: "Compare React, Vue, and Svelte for upcoming projects.",
    assignedUserId: 2,
    taskTypeId: 3,
  },
  {
    id: 8,
    title: "Health checkup appointment",
    status: TaskStatusEnum.InProgress,
    shortDescription: "Schedule annual physical and blood tests.",
    assignedUserId: 0,
    taskTypeId: 2,
  },
  {
    id: 9,
    title: "Organize hobby workshop",
    status: TaskStatusEnum.InProgress,
    shortDescription: "Plan painting workshop for team building.",
    assignedUserId: 1,
    taskTypeId: 3,
  },
  {
    id: 10,
    title: "Refactor API endpoints",
    status: TaskStatusEnum.InProgress,
    shortDescription: "Clean up redundant code and improve performance.",
    assignedUserId: 2,
    taskTypeId: 4,
  },
  {
    id: 11,
    title: "Backlog grooming",
    status: TaskStatusEnum.InProgress,
    shortDescription:
      "Review backlog items and prioritize tasks for next sprint.",
    assignedUserId: 1,
    taskTypeId: 1,
  },
  {
    id: 12,
    title: "Yoga session",
    status: TaskStatusEnum.InProgress,
    shortDescription: "Attend online yoga class for stress relief.",
    assignedUserId: 0,
    taskTypeId: 2,
  },
  {
    id: 13,
    title: "Team brainstorming",
    status: TaskStatusEnum.Done,
    shortDescription: "Discuss new feature ideas and improvements for the app.",
    assignedUserId: 2,
    taskTypeId: 4,
  },
  {
    id: 14,
    title: "Read new tech book",
    status: TaskStatusEnum.Done,
    shortDescription: "Finish reading 'Clean Architecture' and take notes.",
    assignedUserId: 1,
    taskTypeId: 3,
  },
  {
    id: 15,
    title: "Update project documentation",
    status: TaskStatusEnum.Done,
    shortDescription: "Ensure all API endpoints and UI flows are documented.",
    assignedUserId: 0,
    taskTypeId: 4,
  },
  {
    id: 16,
    title: "Backlog review meeting",
    status: TaskStatusEnum.Done,
    shortDescription: "Discuss pending backlog items with the team.",
    assignedUserId: 2,
    taskTypeId: 1,
  },
];
